# Generated by Django 4.2.11 on 2026-05-26 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('medicine_id', models.AutoField(primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=200)),
                ('unit', models.CharField(choices=[('VIEN', 'Viên'), ('VI', 'Vỉ'), ('LO', 'Lọ'), ('CHAI', 'Chai'), ('TUYP', 'Tuýp')], default='VIEN', max_length=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Medicines',
                'ordering': ['medicine_name'],
            },
        ),
    ]
